global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets:
      - localhost:9090

  - job_name: host
    static_configs:
    - targets:
      - 10.129.0.33:9100

  - job_name: orders
    static_configs:
    - targets:
      - 10.129.0.33:8001

  - job_name: nginx
    static_configs:
    - targets:
      - 10.129.0.33:9113

  - job_name: 'blackbox-orders'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://nginx:8080/      
        - http://nginx:8080/order 
        - http://nginx:8080/admin 
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox:9115
